<a href="https://colab.research.google.com/github/Ineyt/data-science-bootcamp/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello Colab!')

Hello Colab!


In [3]:
import numpy as np
np.__version__

'1.21.6'

In [4]:
x = np.array([1, 3])
x

array([1, 3])

In [4]:
print(x)

[1 3]


In [5]:
x.ndim

1

In [6]:
x.size

2

In [9]:
x = np.array([[1,2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [10]:
x.ndim

2

In [11]:
x.shape

(2, 2)

In [12]:
x = np.array([[1, 2, 4], [4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [13]:
x.shape

(2, 3)

In [17]:
x = np.array(
    [[[4,3,1],
      [3,1,2],

      [4,1,3],
       [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2],
        [4, 1, 3],
        [4, 2, 1]]])

In [18]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [20]:
A = np.array([1, 2, 3], dtype=float)
A.dtype
A

array([1., 2., 3.])

In [22]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.full(shape=(5,5), fill_value=4, dtype=int)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])