<a href="https://colab.research.google.com/github/Ineyt/data-science-bootcamp/blob/main/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [2]:
A + B 

array([6, 0, 7, 4])

In [3]:
A - B

array([0, 2, 1, 0])

In [4]:
A * B

array([ 9, -1, 12,  4])

In [5]:
A + 3

array([6, 4, 7, 5])

In [6]:
A * 2

array([6, 2, 8, 4])

In [7]:
A + 3*B

array([12, -2, 13,  8])

In [8]:
np.add(A, B)

array([6, 0, 7, 4])

In [9]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [10]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [11]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [13]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X) 
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [14]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [15]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [16]:
np.random.seed(0)

In [17]:
np.random.randn()

1.764052345967664

In [18]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [19]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [20]:
np.random.rand()

0.1965823616800535

In [21]:
np.random.rand(10,2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [22]:
np.random.randint(10)

1

In [23]:
np.random.randint(low=10, high=101)

60

In [24]:
np.random.randint(low=10, high=101, size=10)

array([37, 24, 51, 68, 75, 46, 20, 96, 53, 21])

In [25]:
np.random.choice([4, 5, 6, 8])

6

In [26]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.random.shuffle(data)
data

array([5, 1, 4, 2, 9, 7, 6, 8, 0, 3])

In [2]:
np.exp(1)

2.718281828459045

In [3]:
np.sqrt(4)

2.0

In [4]:
np.all([1,2,3])

True

In [5]:
np.any([1,0,0])

True

In [6]:
A = np.random.rand(5)
A

array([0.69374488, 0.20764352, 0.44526211, 0.39394153, 0.32887936])

In [7]:
A[np.argmax(A)]

0.6937448774873565

In [8]:
A[np.argmin(A)]

0.20764351982445972

In [9]:
np.max(A)

0.6937448774873565

In [10]:
np.mean(A)

0.4138942782656301

In [3]:
A = np.arange(20)

A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
A[2]

2

In [4]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [5]:
A[:2]

array([0, 1])

In [6]:
A[[0, 2]]

array([0, 2])

In [7]:
A[-1]

19

In [8]:
A[10:15]

array([10, 11, 12, 13, 14])

In [4]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
A[0]

array([0, 1, 2, 3, 4])

In [11]:
A[1]

array([5, 6, 7, 8, 9])

In [13]:
A[:,-1]

array([ 4,  9, 14, 19])

In [14]:
A[1,1]

6

In [6]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [7]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [8]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [14]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [15]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])